version: "3.9"
services:
  postgres:
    ports: 
      - 5433:5432
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "gitgame_db"
      POSTGRES_PASSWORD: "gitgame_password"
volumes:
  postgres_data: