version: "3.9"
services:
  postgres:
    ports: 
      - 5432:5432
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD="postgres"
      - POSTGRES_USER=postgres
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    command: redis-server --loglevel warning
    volumes:
      - redis_data:/data
  ws-server:
    build: ./ws-server/
    image: ws-server
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --log-config ./log.ini
    ports:
      - 8000:8000
  api-server:
    build: ./api-server/
    image: api-server
    command: uvicorn main:app --host 0.0.0.0 --port 8001 --log-config ./log.ini
    ports:
      - 8001:8001
volumes:
  postgres_data:
  redis_data:
