version: "3.9"
services:
  postgres:
    ports: 
      - 5433:5432
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "gitgame_db"
      POSTGRES_PASSWORD: "gitgame_password"
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    command: redis-server --loglevel warning
    volumes:
      - redis_data:/data
  ws-server:
    build: ./ws-server/
    image: ws-server
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload --log-config ./log.ini
    ports:
      - 8000:8000
    volumes:
      - ./ws-server:/code
  api-server:
    build: ./api-server/
    image: api-server
    command: 
      - sh 
      - -c 
      - | 
        pip install --no-cache-dir --upgrade -r requirements.txt
        uvicorn main:app --host 0.0.0.0 --port 8001 --log-config ./log.ini
    ports:
      - 8001:8001
    volumes:
      - ./api-server:/code
    depends_on:
      - postgres
volumes:
  postgres_data:
  redis_data:
