name: Frontend Builder

on:
  workflow_dispatch:
  
  push:
    branches: [actions-test]
    paths-ignore: 
      - 'client/build/**'
    
jobs:
  kickoff:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: actions-test

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install Packages
      run: |
        cd client
        npm install

    - name: Build App
      run: |
        cd client
        CI=false REACT_APP_HTTP_ENDPOINT=${{ vars.REACT_APP_HTTP_ENDPOINT }} REACT_APP_WS_ENDPOINT=${{ vars.REACT_APP_WS_ENDPOINT }} npm run build

    - name: Push Build!
      run: |
        git config --global user.name "gitgame.builder"
        git config --global user.email "gitgame.builder@github.com"
        git add client/build --force
        git commit -m "build client of ${{ github.sha }}"
        git push -f
    