# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test on Pull Request

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Run Tests
      env:
        GITHUB_ACCESS_TOKEN: ${{secrets.TOKEN}}
      run: |
        cd ./server
        pip install -r requirements.txt
        pip install -e .
        pytest
